# Generated by Django 4.1.5 on 2023-01-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='decription',
            new_name='description',
        ),
    ]
